### ISSUE TITLE
response

### ISSUE THREAD

**Issue by mk3174** [Indreshkashyap/vb.net#1]
bro i have doubts can u contact me please. 9908244749 i have doubts in this project which is very necessary right now. due for my project is also near so please look through and call or message.

**Comment by Indreshkashyap** [comment]
what kind of doubt please tell me.. if possible then i solve

**Comment by mk3174** [comment]
Bro it's complicated can you give me your number so I can contact in
whatsapp

**Comment by Indreshkashyap** [comment]
please tell me here ..if possible i solve your issues.. here any kind of codes you share with me... sorry i'm not share my mobile number.

**Comment by mk3174** [comment]
I got some doubts on fingerprint based atm system. I need the databases codes

**Comment by Indreshkashyap** [comment]
It is complete project.. Please open this project on visual studio and run.. And put ms acess file path on databae files according to your system then project is running very well.. And if you want to connect with other database like mysql, sql server then you just change drivename and path then it is working.. Good luck

**Comment by mk3174** [comment]
we wanna do this without scanner so if u could help somehow?

where to run the codes means on which software

**Comment by Indreshkashyap** [comment]
this is .exe (https://github.com/Indreshkashyap/vb.net/blob/main/AtmSystem/bin/Debug/WindowsApplication5.exe)

this is ms acess database file (https://github.com/Indreshkashyap/vb.net/blob/main/AtmSystem/ind.accdb)

above WindowsApplication5.exe file is directly run on windows you can just double click on it.
and ind.accdb is database file you can open it and use stored data like id password of atm system..

**Comment by Indreshkashyap** [comment]
and also edit codes through  microsoft VISUAL STUDIO 2008 and above version(https://visualstudio.microsoft.com/vs/older-downloads/)
FILE - OPEN  - RUN

**Comment by Indreshkashyap** [comment]
and if you want to use scanner then you use with with your windows login id password and put your project on startup otherwise dont do anything just download code and click .exe file
